-- 1. Create a profiles table to store extra user metadata
-- This table will be linked to Supabase's built-in Auth system
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  name TEXT,
  username TEXT UNIQUE,
  email TEXT UNIQUE,
  location TEXT,
  is_admin BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create the design_history table
CREATE TABLE public.design_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  theme TEXT,
  space_type TEXT,
  budget INTEGER,
  total_cost INTEGER,
  selected_plan TEXT,
  design_intensity TEXT,
  image_url TEXT,
  procurement_plans_json TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. (Optional but recommended) Set up Row Level Security (RLS)
-- For now, we will disable RLS to match your "SQLite simplicity" 
-- so you can test quickly. You can enable it later for production.
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.design_history ENABLE ROW LEVEL SECURITY;

-- Allow all access for now (Development Mode)
CREATE POLICY "Allow everything for everyone" ON public.profiles FOR ALL USING (true);
CREATE POLICY "Allow everything for everyone" ON public.design_history FOR ALL USING (true);
